cd /home/sec312/package/qdbb/test
echo PID ${PID}
echo D ${D}
echo A ${A}
echo T ${T}
echo X ${X}
echo B ${B}
echo C ${C}
echo S ${S}
echo CP ${CP}
echo R ${R}
echo RSK ${RSK}
echo L ${L}
echo I ${I}
echo P ${P}
echo OT ${OT}
echo ./portfolio -d ${D} -a ${A} -t ${T} -x ${X} -b ${B} -c ${C} -s ${S} -C ${CP} -r ${R} -risk ${RSK} -k ${k} -l ${L} -i ${I} -p ${P} -ot ${OT} -ct quadratic -o 2
./portfolio -d ${D} -a ${A} -t ${T} -x ${X} -b ${B} -c ${C} -s ${S} -C ${CP} -r ${R} -risk ${RSK} -k ${k} -l ${L} -i ${I} -p ${P} -ot ${OT} -ct quadratic -o 2
